language: node_js
node_js:
    - "8.9"
addons:
  postgresql: "9.3"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - npm test
  - npm run test_pg
  - npm run linter
before_script:
  - psql -c 'create database counter;' -U postgres
git:
    submodules: false
env:
  - CXX=g++-4.8 TEST_PG_CONNECTION_STRING=postgres://postgres@localhost:5432/counter
